// Generated by scripts/generate-hdr-sharpen-curve.py; do not edit.
vec3 sharpenCurveToe(vec3 x)
{
    vec3 numerator = vec3(5.5894315815e+02);
    numerator = numerator * x + vec3(2.1924259412e+02);
    numerator = numerator * x + vec3(2.2047696281e+00);
    numerator = numerator * x + vec3(8.8938689503e-04);
    numerator = numerator * x + vec3(0.0000000000e+00);
    vec3 denominator = vec3(-3.9319540009e+03);
    denominator = denominator * x + vec3(2.9050606114e+03);
    denominator = denominator * x + vec3(-1.1065700262e+03);
    denominator = denominator * x + vec3(2.1935057120e+02);
    denominator = denominator * x + vec3(1.0000000000e+00);
    return numerator / denominator;
}
vec3 sharpenCurveMain(vec3 x)
{
    vec3 numerator = vec3(4.7768956897e-02);
    numerator = numerator * x + vec3(4.5984182358e-01);
    numerator = numerator * x + vec3(6.9531775314e-01);
    numerator = numerator * x + vec3(-5.6369248851e-02);
    vec3 denominator = vec3(-2.7988485701e-02);
    denominator = denominator * x + vec3(4.6718461576e-01);
    denominator = denominator * x + vec3(-1.3891074009e+00);
    denominator = denominator * x + vec3(1.1663933305e+00);
    return numerator / denominator;
}
vec3 sharpenCode(vec3 pq)
{
    vec3 x = clamp(pq, 0.0, 1.0);
    bvec3 toe = lessThanEqual(x, vec3(0.125));
    if (all(toe)) return sharpenCurveToe(x);
    if (!any(toe)) return sharpenCurveMain(x);
    return mix(sharpenCurveMain(x), sharpenCurveToe(x), toe);
}

vec3 sharpenPqCurve(vec3 code)
{
    vec3 x = (code - vec3(4.0450000000e-02)) * 1.9026277892e-01;
    vec3 numerator = vec3(9.6531207172e+01);
    numerator = numerator * x + vec3(2.6773477323e+02);
    numerator = numerator * x + vec3(1.1065934254e+02);
    numerator = numerator * x + vec3(9.3228228118e+00);
    numerator = numerator * x + vec3(1.2806491152e-01);
    vec3 denominator = vec3(6.0026154413e+01);
    denominator = denominator * x + vec3(2.3939210607e+02);
    denominator = denominator * x + vec3(1.5823587509e+02);
    denominator = denominator * x + vec3(2.5722324359e+01);
    denominator = denominator * x + vec3(1.0000000000e+00);
    return clamp(numerator / denominator, 0.0, 1.0);
}
