#!/usr/bin/env python3
"""Generate the PQ-to-sharpening-code approximation; no image, descriptor or runtime upload.

The filters expect bounded SDR-like code values. This curve maps ST 2084
BT.2020 components into an extended sRGB transfer curve at 203 nits, retaining
BT.2020 primaries and HDR values above one. Local normalization in the filter
preserves those highlights. A fourth-degree toe and third-degree main rational piece replace per-tap powers.
The reverse main curve uses a fourth-degree rational approximation; the dark toe stays analytic.
"""
import argparse
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / 'src/shader/hdr_sharpen_curve.glsl'
# Weighted least-squares rational fits to the analytic PQ -> extended-sRGB
# function below on [0, 0.125] and [0.125, 1]. Coefficients are low to high.
# The dense check bounds transfer error and rejects poles/non-monotonic curves.
NUM = ((0.0, .0008887926933800804, 2.2032966159100473, 219.09611758883287, 558.5697268049421),
       (-0.0563692488511675, 0.6953177531379342, 0.4598418235834362, 0.04776895689741686))
DEN = ((1.0, 219.35057119961562, -1106.5700261686347, 2905.0606114462803, -3931.9540009292323),
       (1.166393330502013, -1.389107400897217, 0.46718461576152975, -0.02798848570103502))

# Match the two pieces at the join so neighbourhood extrema remain valid.
def evaluate(coefficients, x):
    return sum(value * x**i for i, value in enumerate(coefficients))
join = .125
join_scale = (evaluate(NUM[1], join) / evaluate(DEN[1], join)) / (evaluate(NUM[0], join) / evaluate(DEN[0], join))
NUM = (tuple(value * join_scale for value in NUM[0]), NUM[1])

def decode(pq):
    p = pq ** (32.0 / 2523.0)
    return (max(p - 3424.0 / 4096.0, 0.0) / (2413.0 / 128.0 - 2392.0 / 128.0 * p)) ** (16384.0 / 2610.0) * (10000.0 / 203.0)

def code(pq):
    linear = decode(pq)
    return 12.92 * linear if linear <= 0.0031308 else 1.055 * linear ** (1.0 / 2.4) - 0.055

# Reverse fit in normalized coordinates across the non-linear sRGB segment.
# Below this segment retain the analytic linear-sRGB/PQ composition.
ENC_START = 0.04045
ENC_END = code(1.0)
ENC_NUM = (0.12806200257299663, 9.322822811787915, 110.65934253773482, 267.73477322654526, 96.53120717181041)
ENC_DEN = (1.0, 25.722324358614117, 158.23587508967395, 239.3921060705366, 60.02615441339204)

def encode(value):
    linear = value / 12.92 if value <= ENC_START else ((value + .055) / 1.055) ** 2.4
    p = min(max(linear * 203 / 10000, 0), 1) ** (2610 / 16384)
    return ((3424 / 4096 + 2413 / 128 * p) / (1 + 2392 / 128 * p)) ** (2523 / 32)

# Preserve the exact transfer join instead of allowing a discontinuity.
ENC_NUM = (encode(ENC_START), *ENC_NUM[1:])

def literal(value):
    return format(value, '.10e')

def render():
    lines=['// Generated by scripts/generate-hdr-sharpen-curve.py; do not edit.']
    for side,label in [(0,'Toe'),(1,'Main')]:
        lines += [f'vec3 sharpenCurve{label}(vec3 x)', '{']
        for name,coefs in [('numerator',NUM[side]),('denominator',DEN[side])]:
            for i in reversed(range(len(coefs))):
                if i==len(coefs)-1:lines.append(f'    vec3 {name} = vec3({literal(coefs[i])});')
                else:lines.append(f'    {name} = {name} * x + vec3({literal(coefs[i])});')
        lines+=['    return numerator / denominator;', '}']
    lines += ['vec3 sharpenCode(vec3 pq)', '{', '    vec3 x = clamp(pq, 0.0, 1.0);',
        '    bvec3 toe = lessThanEqual(x, vec3(0.125));',
        '    if (all(toe)) return sharpenCurveToe(x);',
        '    if (!any(toe)) return sharpenCurveMain(x);',
        '    return mix(sharpenCurveMain(x), sharpenCurveToe(x), toe);', '}', '']
    lines += ['vec3 sharpenPqCurve(vec3 code)', '{',
        f'    vec3 x = (code - vec3({literal(ENC_START)})) * {literal(1 / (ENC_END - ENC_START))};']
    for name, coefs in [('numerator', ENC_NUM), ('denominator', ENC_DEN)]:
        for i in reversed(range(len(coefs))):
            if i == len(coefs)-1: lines.append(f'    vec3 {name} = vec3({literal(coefs[i])});')
            else: lines.append(f'    {name} = {name} * x + vec3({literal(coefs[i])});')
    lines += ['    return clamp(numerator / denominator, 0.0, 1.0);', '}', '']
    return '\n'.join(lines)

def validate():
    import struct
    def f32(value):
        return struct.unpack('f', struct.pack('f', value))[0]
    def adjacent(value, offset):
        bits = struct.unpack('I', struct.pack('f', value))[0]
        return struct.unpack('f', struct.pack('I', bits + offset))[0]
    worst = inverse_worst = 0.0
    # Check both separate multiplies/adds and float32-contracted Horner math.
    for fused in (False, True):
        def polynomial(coefficients, x):
            value = 0.0
            for coefficient in reversed(coefficients):
                product = value * x
                value = f32((product if fused else f32(product)) + f32(float(literal(coefficient))))
            return value
        def forward(x):
            side = 0 if x <= .125 else 1
            denominator = polynomial(DEN[side], x)
            assert abs(denominator) > .05
            return f32(polynomial(NUM[side], x) / denominator)
        def reverse(value):
            if value <= f32(ENC_START):
                return encode(value)
            x = f32(f32(value - f32(ENC_START)) * f32(1 / (ENC_END - ENC_START)))
            denominator = polynomial(ENC_DEN, x)
            assert denominator >= 1
            return min(max(f32(polynomial(ENC_NUM, x) / denominator), 0), 1)
        previous = -1.0
        for i in range(65537):
            x = f32(i / 65536)
            y = forward(x)
            assert y >= 0 and y >= previous, (fused, x, y, previous)
            previous = y
            worst = max(worst, abs(encode(y) - x) * 1023, abs(reverse(y) - x) * 1023)
        assert previous > 1
        previous = -1.0
        for i in range(65537):
            value = f32(ENC_START + (ENC_END - ENC_START) * i / 65536)
            y = reverse(value)
            assert y >= previous, (fused, value, y, previous)
            previous = y
            inverse_worst = max(inverse_worst, abs(y - encode(value)) * 1023)
        # Dense grids alone can miss a one-ULP discontinuity at a piece boundary.
        for function, boundary in ((forward, .125), (reverse, ENC_START)):
            values = [function(adjacent(boundary, offset)) for offset in range(-4, 5)]
            assert values == sorted(values), (fused, boundary, values)
        assert forward(0.0) == 0.0
        assert round(reverse(0.0) * 1023) == 0
        assert abs(reverse(f32(ENC_END)) - 1.0) * 1023 < .01
    assert worst < .1, worst
    assert inverse_worst < .01, inverse_worst
    return worst, inverse_worst

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    error,inverse_error=validate();expected=render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text()!=expected:
            raise SystemExit('stale HDR sharpening curve: run scripts/generate-hdr-sharpen-curve.py')
    else: OUTPUT.write_text(expected)
    print(f'HDR sharpening curve: maximum round-trip error {error:.6f} HDR10 LSB; inverse {inverse_error:.6f} HDR10 LSB')
if __name__ == '__main__':main()
